spring:
  datasource:
      driver-class-name: ${azaz.datasource.driver-class-name}
      url: jdbc:mysql://${azaz.datasource.host}:${azaz.datasource.port}/${azaz.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${azaz.datasource.username}
      password: ${azaz.datasource.password}
  redis:
    host: ${azaz.redis.host}
    port: ${azaz.redis.port}
    password: ${azaz.redis.password}
    database: ${azaz.redis.database}
# 配置mybatis
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出
logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info