# 配置mybatis
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出
logging:
  level:
    com:
      azaz:
        mapper: debug
        service: info
        controller: info