spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.176.164:3306/azaz?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: sgc123456
    druid:
      #     配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      time-between-eviction-runs-millis: 300000
      #     保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
  redis:
    host: 124.221.176.164
    port: 6380
    password: sgc123456
    database: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 255MB
      max-request-size: 1024MB
  data:
    mongodb:
      host: 124.221.176.164
      port: 27017
      database: azaz
# 配置mybatis
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出
logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
#配置redisson
redisson:
  address: 'redis://124.221.176.164:6380'